apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
  annotations:
    prometheus.io/port: '10824'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 443
      name: mux
  selector:
    app: helloworld
