apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
      annotations:
        # prometheus annotations by default
        prometheus.io/port: '10824'
        prometheus.io/scrape: 'true'
    spec:
      imagePullSecrets:
        - name: goog-key1
      containers:
        - name: helloworld-container
          image: services/helloworld:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          # should contain a healthcheck path & port; excluded for brevity in this repo
          livenessProbe:
            httpGet:
              path: /swagger.json
              port: 80
          readinessProbe:
            httpGet:
              path: /swagger.json
              port: 80
          env:
            - name: DEPLOY
              value: VERSION
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
  annotations:
    prometheus.io/port: '10824'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 80
      name: frontend
    - port: 1000
      name: grpc
  selector:
    app: helloworld
