name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.4

      - uses: actions/checkout@v4.2.2

      - name: Coverage
        run: make coverage

      - name: Publish code cov
        uses: actions/upload-artifact@v3
        with:
          name: code covarege report
          path: |
            coverage.html
            coverage.txt